### ISSUE TITLE
How can i add my own theme in active admin?

### ISSUE THREAD

**Issue by yasirrose** [paladini/activeadmin-themes#4]
Hi, I have ben struggling to change the default layout of the active admin but got no success. I just want to change the default layout or it would also be helpful If I can install my own theme for active admin. Is there any way to do this?

**Comment by paladini** [comment]
When you say you would like to add your own theme to Active Admin, you mean you would like to use one of the repository's theme and don't know how to install/use it in your Active Admin project?

**Comment by paladini** [comment]
@yasirrose Any news on that matter? Answer when you can, so I can help you :)

**Comment by yasirrose** [comment]
@paladini .. i want to say that i should redesign it according to my theme like layout change etc. 

But now i have removed it and now adding custom views and layouts.
